check-file filename:
    uv run ruff check --no-cache --no-fix {{filename}}
    uv run ruff format --check {{filename}}
    uv run auto-typing-final {{filename}} --check
    uv run mypy --config-file pyproject.toml {{filename}}

test *args:
    .venv/bin/pytest -n auto {{args}}
