install:
    uv sync

check-file filename:
    .venv/bin/ruff check --no-fix {{filename}}
    .venv/bin/ruff format --check {{filename}}
    .venv/bin/auto-typing-final --check {{filename}}
    .venv/bin/flake8 --select COP {{filename}}

test *args: install
    .venv/bin/pytest -n 16 -v {{args}}
