#!/usr/bin/env bash
# Refresh pylines guides cache from GitHub. Safe offline (keeps old cache).
set -u
REPO="https://github.com/community-of-python/pylines"
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE_ROOT="${PYLINES_CACHE_DIR:-$SKILL_DIR/cache}"
DIR="$CACHE_ROOT/pylines"
STAMP="$CACHE_ROOT/.fetch-stamp"
INDEX="$CACHE_ROOT/index.md"
TTL_MIN="${PYLINES_TTL_MIN:-60}"
unset HTTPS_PROXY HTTP_PROXY https_proxy http_proxy  # public host: claude-fwd proxy is Anthropic-only

# Map every guide's headings to line numbers, skipping fenced code blocks so that
# Python comments like "# Плохо:" are not mistaken for headings.
build_index() {
  {
    echo "# pylines guides — index"
    echo
    echo "Generated by sync.sh on every run. Do not edit; edit the guides upstream."
    echo "Guides directory: $DIR"
    for guide in "$DIR"/*.md; do
      [ "${guide##*/}" = "README.md" ] && continue
      printf '\n## %s — %s lines\n' "${guide##*/}" "$(wc -l < "$guide" | tr -d ' ')"
      awk '
        /^ *```/            { fenced = !fenced; next }
        !fenced && /^ *#+ / { heading = $0; sub(/^ *#+ +/, "", heading); printf "  L%-5d %s\n", NR, heading }
      ' "$guide"
    done
  } > "$INDEX"
}

if [ ! -d "$DIR/.git" ]; then
  mkdir -p "$CACHE_ROOT"
  git clone --depth 1 -q "$REPO" "$DIR" || { echo "pylines: no cache and clone failed"; exit 1; }
  touch "$STAMP"
  status="cloned ($(git -C "$DIR" rev-parse --short HEAD))"
elif [ "$TTL_MIN" -gt 0 ] && [ -n "$(find "$STAMP" -mmin "-$TTL_MIN" 2>/dev/null)" ]; then
  status="cache fresh (<${TTL_MIN}m, $(git -C "$DIR" rev-parse --short HEAD))"
elif git -C "$DIR" fetch --depth 1 -q origin main && git -C "$DIR" reset --hard -q origin/main; then
  touch "$STAMP"
  status="updated ($(git -C "$DIR" rev-parse --short HEAD))"
else
  status="fetch failed (offline?) — using cached copy"
fi

build_index

echo "$status"
echo "guides: $DIR"
echo "index:  $INDEX"
