from __future__ import annotations
import typing


MIN_NAME_LENGTH: typing.Final = 8

VERB_PREFIXES: typing.Final = {
    "validate",
    "execute",
    "visit",
    "get",
    "cancel",
    "retrieve",
    "lock",
    "assert",
    "extract",
    "enrich",
    "run",
    "patch",
    "build",
    "start",
    "ping",
    "prepare",
    "publish",
    "request",
    "ack",
    "nack",
    "reject",
    "stop",
    "route",
    "begin",
    "subscribe",
    "connect",
    "close",
    "enter",
    "exit",
    "take",
    "dump",
    "iter",
    "escape",
    "unescape",
    "add",
    "contains",
    "unsubscribe",
    "resubscribe",
    "commit",
    "raise",
    "mock",
    "produce",
    "consume",
    "track",
    "wait",
    "bootstrap",
    "calculate",
    "check",
    "collect",
    "compute",
    "convert",
    "create",
    "delete",
    "fetch",
    "find",
    "format",
    "generate",
    "handle",
    "has",
    "is",
    "list",
    "load",
    "make",
    "parse",
    "process",
    "read",
    "receive",
    "remove",
    "render",
    "resolve",
    "save",
    "send",
    "set",
    "should",
    "update",
    "write",
}

SCALAR_ANNOTATIONS: typing.Final = {"int", "str", "float", "bool", "bytes", "complex"}

MAPPING_PROXY_TYPES: typing.Final = {"MappingProxyType"}

ALLOWED_STDLIB_FROM_IMPORTS: typing.Final = {"collections.abc"}

FINAL_CLASS_EXCLUDED_BASES: typing.Final = {"BaseModel", "RootModel", "ModelFactory"}
