from __future__ import annotations

MIN_NAME_LENGTH = 8

VERB_PREFIXES = {
    "get",
    "enrich",
    "run",
    "patch",
    "build",
    "start",
    "ping",
    "publish",
    "request",
    "ack",
    "nack",
    "reject",
    "stop",
    "route",
    "begin",
    "subscribe",
    "connect",
    "close",
    "enter",
    "exit",
    "take",
    "dump",
    "iter",
    "escape",
    "unescape",
    "add",
    "contains",
    "unsubscribe",
    "resubscribe",
    "commit",
    "raise",
    "mock",
    "produce",
    "consume",
    "track",
    "wait",
    "bootstrap",
    "calculate",
    "check",
    "collect",
    "compute",
    "convert",
    "create",
    "delete",
    "fetch",
    "find",
    "format",
    "generate",
    "handle",
    "has",
    "is",
    "list",
    "load",
    "make",
    "parse",
    "process",
    "read",
    "receive",
    "remove",
    "render",
    "resolve",
    "save",
    "send",
    "set",
    "should",
    "update",
    "validate",
    "write",
}

SCALAR_ANNOTATIONS = {"int", "str", "float", "bool", "bytes", "complex"}

MAPPING_PROXY_TYPES = {"MappingProxyType"}
